# conversation_state.py

class ConversationStates:

    INITIAL = "INITIAL"

    SEARCH_RESULTS = "SEARCH_RESULTS"

    AWAITING_SELECTION = "AWAITING_SELECTION"

    AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"

    DOCUMENT_DETAIL = "DOCUMENT_DETAIL"

    NOTIFICATION_LIST = "NOTIFICATION_LIST"

    NOTIFICATION_SELECTION = "NOTIFICATION_SELECTION"

    AWAITING_POST_DETAIL_DECISION = "AWAITING_POST_DETAIL_DECISION"

    CONTACT_FLOW = "CONTACT_FLOW"